# -*- coding: utf-8 -*-
"""capstone project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubXtYGTY59M5H3zwjjLKv6md9xZwoIDv
"""

from google.colab import drive
drive.mount('/content/drive')

import os
SAVE_FOLDER = '/content/drive/MyDrive/MarketResearchReports'
os.makedirs(SAVE_FOLDER, exist_ok=True)
print("✅ Google Drive connected! Reports will save to:", SAVE_FOLDER)

!pip install gradio langchain langchain-groq langchain-community langchain-huggingface faiss-cpu pypdf sentence-transformers

from google.colab import userdata
import os, json, traceback
import gradio as gr
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_community.vectorstores import FAISS
from langchain_community.document_loaders import PyPDFLoader, TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

try:
    from langchain_huggingface import HuggingFaceEmbeddings
except ImportError:
    from langchain_community.embeddings import HuggingFaceEmbeddings

print("✅ All imports successful!")

!pip install fpdf2

RESEARCH_HUMAN = """You are a senior market research analyst.

Industry: {industry}
Business Idea: {business_idea}
Extra context: {rag_context}

Return ONLY a valid JSON object — no markdown fences, no extra text — with exactly these keys:
{{
  "market_size": "<string like '$142 Billion'>",
  "top_competitors": ["Company1 - desc", "Company2 - desc", "Company3 - desc", "Company4 - desc", "Company5 - desc"],
  "swot_analysis": {{
    "strengths": "<string>",
    "weaknesses": "<string>",
    "opportunities": "<string>",
    "threats": "<string>"
  }}
}}"""

STRATEGY_HUMAN = """You are a bold, creative CMO. Be specific. Avoid generic advice.

Industry: {industry} | Idea: {business_idea}
Market: {market_size} | Competitors: {competitors} | SWOT: {swot_summary}

Write a sharp 250-350 word go-to-market strategy covering:
1. A memorable one-sentence positioning statement.
2. The single highest-leverage acquisition channel for Year 1 with a specific tactic.
3. A differentiation move competitors would find difficult to copy.
4. One contrarian insight most founders in this space miss.
Write in flowing paragraphs, no bullet points."""

print("✅ Prompts ready!")

_EMBEDDINGS = None

def get_embeddings():
    global _EMBEDDINGS
    if _EMBEDDINGS is None:
        print("⏳ Loading embedding model (~30 seconds first time)...")
        _EMBEDDINGS = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
        print("✅ Embedding model ready!")
    return _EMBEDDINGS

def get_llm(temperature):
    api_key = os.environ.get("GROQ_API_KEY", "").strip()
    return ChatGroq(
        model="llama-3.1-8b-instant",
        temperature=temperature,
        groq_api_key=api_key,
    )

def build_vectorstore(file_obj):
    if file_obj is None:
        return None
    path = file_obj if isinstance(file_obj, str) else getattr(file_obj, "name", None)
    if not path:
        return None
    try:
        loader = PyPDFLoader(path) if path.lower().endswith(".pdf") else TextLoader(path)
        docs   = loader.load()
        chunks = RecursiveCharacterTextSplitter(
            chunk_size=600, chunk_overlap=60
        ).split_documents(docs)
        return FAISS.from_documents(chunks, get_embeddings())
    except Exception as e:
        print(f"⚠️ Document error: {e}")
        return None

def retrieve_context(vs, query):
    if vs is None:
        return "No document uploaded."
    try:
        return "\n\n".join(d.page_content for d in vs.similarity_search(query, k=5))
    except Exception:
        return "Could not retrieve context."

def error_result(msg):
    return msg, "", "", "", "❌ Failed", ""

print("✅ Helper functions ready!")

from fpdf import FPDF
import datetime

def export_to_pdf(mkt_text, comp_text, swot_text, strat_text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(200, 10, "Market Research Report", ln=True, align="C")
    pdf.set_font("Arial", "", 10)
    pdf.cell(200, 10, f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align="C")
    pdf.ln(5)

    for title, content in [("Market Analysis", mkt_text),
                            ("Competitor Analysis", comp_text),
                            ("SWOT Analysis", swot_text),
                            ("Strategy", strat_text)]:
        pdf.set_font("Arial", "B", 12)
        pdf.cell(200, 10, title, ln=True)
        pdf.set_font("Arial", "", 10)
        # Handle special characters
        safe_content = (content or "").encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 8, safe_content)
        pdf.ln(3)

    filename = f"market_report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    pdf.output(filename)
    return filename

!pip install fpdf2

def run_analysis(industry, business_idea, file_obj):

    # --- Load API Key from Colab Secrets ---
    try:
        api_key = userdata.get("GROQ_API_KEY")
        if not api_key or not api_key.strip():
            return error_result("❌ Groq API key not found. Please add it to Colab Secrets under the name GROQ_API_KEY.")
        os.environ["GROQ_API_KEY"] = api_key.strip()
        print(f"✅ Groq API key loaded (starts with: {api_key[:8]})...")
    except Exception as e:
        return error_result(f"❌ Could not read Groq API key from Colab Secrets: {e}")

    # --- Check that user filled in the fields ---
    industry      = str(industry).strip()
    business_idea = str(business_idea).strip()
    if not industry or not business_idea:
        return error_result("⚠️ Please fill in both the Industry and Business Idea fields.")

    # --- Handle uploaded document ---
    rag_status = "ℹ️ No document — using LLM knowledge only"
    vs = None
    if file_obj is not None:
        print("📄 Processing uploaded document...")
        vs = build_vectorstore(file_obj)
        rag_status = "✅ Document indexed!" if vs else "⚠️ Document failed — using LLM only"

    rag_ctx = retrieve_context(vs, f"{industry} {business_idea}")

    # --- First AI Call: Market Research ---
    print("🔍 Calling AI for market research...")
    try:
        raw = (
            ChatPromptTemplate.from_messages([("human", RESEARCH_HUMAN)])
            | get_llm(0.2)
            | StrOutputParser()
        ).invoke({
            "industry":      industry,
            "business_idea": business_idea,
            "rag_context":   rag_ctx,
        })
        print("✅ Research done!")
    except Exception as e:
        traceback.print_exc()
        err = str(e)
        if any(x in err.upper() for x in ["API_KEY", "INVALID", "401", "403", "AUTHENTICATION"]):
            return error_result("❌ Groq rejected your API key. Please check your GROQ_API_KEY in Colab Secrets.")
        return error_result(f"❌ AI error: {err}")

    # --- Parse the JSON response ---
    cleaned = raw.strip()
    for fence in ["```json", "```JSON", "```"]:
        cleaned = cleaned.replace(fence, "")
    start = cleaned.find("{")
    end   = cleaned.rfind("}") + 1
    if start == -1 or end <= start:
        return error_result(f"❌ No JSON found in response.\n\nRaw:\n{raw[:500]}")
    try:
        data = json.loads(cleaned[start:end])
    except json.JSONDecodeError as e:
        return error_result(f"❌ JSON parse error: {e}")

    # --- Extract the data pieces ---
    swot        = data.get("swot_analysis") or {}
    competitors = data.get("top_competitors") or []
    market_size = data.get("market_size", "N/A")
    if not isinstance(swot, dict):        swot = {}
    if not isinstance(competitors, list): competitors = []

    swot_summary = (
        f"Strengths: {swot.get('strengths','N/A')} | "
        f"Weaknesses: {swot.get('weaknesses','N/A')} | "
        f"Opportunities: {swot.get('opportunities','N/A')} | "
        f"Threats: {swot.get('threats','N/A')}"
    )
    swot_display = (
        f"✅ STRENGTHS:\n{swot.get('strengths','N/A')}\n\n"
        f"⚠️  WEAKNESSES:\n{swot.get('weaknesses','N/A')}\n\n"
        f"🌱 OPPORTUNITIES:\n{swot.get('opportunities','N/A')}\n\n"
        f"🔴 THREATS:\n{swot.get('threats','N/A')}"
    )
    competitors_display = (
        "\n".join(f"{i+1}. {c}" for i, c in enumerate(competitors))
        or "No competitors returned."
    )

    # --- Second AI Call: Go-to-Market Strategy ---
    print("🚀 Generating go-to-market strategy...")
    try:
        strategy = (
            ChatPromptTemplate.from_messages([("human", STRATEGY_HUMAN)])
            | get_llm(0.8)
            | StrOutputParser()
        ).invoke({
            "industry":      industry,
            "business_idea": business_idea,
            "market_size":   market_size,
            "competitors":   ", ".join(competitors[:3]),
            "swot_summary":  swot_summary,
        })
        print("✅ Strategy done!")
    except Exception as e:
        traceback.print_exc()
        strategy = f"⚠️ Strategy failed: {e}"

    # --- Return all results to the UI ---
    return (
        market_size,
        competitors_display,
        swot_display,
        strategy,
        rag_status,
        json.dumps(data, indent=2),
    )

print("✅ Main function ready!")

import json, datetime

def save_report_to_drive(industry, idea, mkt, comp, swot, strat):
    report = {
        "date": datetime.datetime.now().strftime('%Y-%m-%d %H:%M'),
        "industry": industry,
        "business_idea": idea,
        "market_analysis": mkt,
        "competitor_analysis": comp,
        "swot": swot,
        "strategy": strat
    }
    filename = f"{SAVE_FOLDER}/report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(filename, 'w') as f:
        json.dump(report, f, indent=2)
    print(f"✅ Report saved to Drive: {filename}")

import gradio as gr

with gr.Blocks(title="Market Research Engine", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 📊 Automated Market Research Engine")
    gr.Markdown("*Powered by Groq · LangChain · FAISS RAG*")
    gr.Markdown("---")

    with gr.Row():
        with gr.Column(scale=2):
            industry_box = gr.Textbox(
                label="🏭 Industry",
                placeholder="e.g. EdTech, FinTech, SaaS, Health & Wellness"
            )
            idea_box = gr.Textbox(
                label="💡 Business Idea",
                lines=4,
                placeholder="Describe your concept in 1–3 sentences."
            )
        with gr.Column(scale=1):
            file_in = gr.File(
                label="📄 Upload Report — Optional (PDF or TXT)",
                file_types=[".pdf", ".txt"]
            )

    run_btn = gr.Button("🔍 Run Market Research", variant="primary", size="lg")
    gr.Markdown("---")

    with gr.Row():
        mkt_out = gr.Textbox(label="💰 Total Addressable Market", scale=2)
        rag_out = gr.Textbox(label="📄 Document Used?",           scale=1)

    comp_out  = gr.Textbox(label="🏢 Top 5 Competitors",     lines=7)
    swot_out  = gr.Textbox(label="🔲 SWOT Analysis",         lines=12)
    strat_out = gr.Textbox(label="🚀 Go-to-Market Strategy", lines=14)

    with gr.Accordion("🔧 Raw JSON", open=False):
        json_out = gr.Code(language="json")

    run_btn.click(
        fn=run_analysis,
        inputs=[industry_box, idea_box, file_in],
        outputs=[mkt_out, comp_out, swot_out, strat_out, rag_out, json_out],
    )

print("✅ Launching app...")
demo.launch(share=True, debug=True)

export_btn = gr.Button("📄 Export as PDF")
pdf_output = gr.File(label="Download PDF Report")

# Connect the button (add this near your other .click() connections)
export_btn.click(
    fn=export_to_pdf,
    inputs=[mkt_out, comp_out, swot_out, strat_out],
    outputs=[pdf_output]
)

# Find your main function (the one connected to "Run Market Research" button)
# At the very end of that function, before the return statement, add:
save_report_to_drive(industry, idea, mkt_result, comp_result, swot_result, strat_result)